### ISSUE TITLE
[FEATURE] 개발 환경설정

### ISSUE THREAD

**Issue by CokeLee777** [swyg-goorm/api_server#1]
## Description

각 프로파일에 따른 환경설정

## To-do
- [x] 테스트, 개발, 프로덕션 환경 분리 및 설정
- [x] Dockerfile 분리해서 작성
- [x] 엔티티 클래스 추가 및 매핑
