### ISSUE TITLE
[FEATURE] 테스트 화면 불러오기 기능 구현

### ISSUE THREAD

**Issue by CokeLee777** [swyg-goorm/api_server#5]
## Description

테스트 화면을 불러오기 위한 기능인 "/tests" API 기능을 구현한다.

## To-do
- [x] 더미 데이터 추가 로직 작성
- [x] 비즈니스 로직 작성 및 서비스단 분리
- [x] 예외 처리
- [x] 단위 테스트 및 통합 테스트
