### ISSUE TITLE
[FEATURE] 테스트에 대한 답변 전달 및 총 테스트 유저 수 API 구현

### ISSUE THREAD

**Issue by CokeLee777** [swyg-goorm/api_server#6]
## Description

- 테스트가 완료되고 결과보기 버튼을 누르면 답변을 전달하는 API를 구현한다.
- 결과보기 버튼을 눌러서 테스트를 완료한 유저 수를 전달하는 API를 구현한다.

## To-do
- [x] 비즈니스 로직 작성 및 서비스단 분리
- [x] Openfeign으로 Flask 서버에게 질문에 대한 답변 전달 및 응답으로 취미 및 취미유형을 받는 로직 구현
- [x] 예외처리
- [x] 단위 테스트 및 통합 테스트
